/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health-check': {
    get: operations['HealthCheckController_getMyEmployer'];
  };
}

export interface components {
  schemas: {
    HealthCheckDto: {
      healthy: boolean;
    };
    HealthCheckResponse: {
      data: components['schemas']['HealthCheckDto'];
    };
  };
}

export interface operations {
  HealthCheckController_getMyEmployer: {
    parameters: {};
    responses: {
      /** Health check endpoint */
      200: {
        content: {
          'application/json': components['schemas']['HealthCheckResponse'];
        };
      };
    };
  };
}

export interface external {}
